/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "primary-container": "#dbe3f0",
        "tertiary": "#8a512f",
        "on-primary-container": "#4a525d",
        "primary-fixed": "#dbe3f0",
        "surface-container-high": "#e9e8e4",
        "secondary": "#605f5c",
        "secondary-dim": "#545350",
        "tertiary-fixed": "#f7ad84",
        "surface-tint": "#58606b",
        "on-secondary-fixed-variant": "#5c5b58",
        "on-primary": "#f7f9ff",
        "surface-container-low": "#f5f3f0",
        "surface-variant": "#e3e3de",
        "secondary-fixed-dim": "#d7d4d0",
        "on-surface": "#313330",
        "surface-bright": "#fbf9f6",
        "inverse-primary": "#e9f1fe",
        "inverse-on-surface": "#9e9d9a",
        "on-primary-fixed": "#38404a",
        "on-surface-variant": "#5e5f5c",
        "on-secondary-fixed": "#403f3d",
        "on-tertiary-fixed-variant": "#683616",
        "surface": "#fbf9f6",
        "surface-dim": "#dadad6",
        "on-tertiary-container": "#5d2e0e",
        "primary": "#58606b",
        "error-dim": "#67040d",
        "secondary-fixed": "#e5e2de",
        "tertiary-fixed-dim": "#e8a078",
        "on-secondary": "#fcf8f4",
        "surface-container": "#efeeea",
        "on-secondary-container": "#52524f",
        "outline": "#7a7b77",
        "primary-fixed-dim": "#cdd5e2",
        "on-primary-fixed-variant": "#545c67",
        "secondary-container": "#e5e2de",
        "tertiary-dim": "#7b4524",
        "outline-variant": "#b2b2ae",
        "on-tertiary-fixed": "#421900",
        "surface-container-highest": "#e3e3de",
        "inverse-surface": "#0e0e0d",
        "on-tertiary": "#fff7f5",
        "on-error": "#fff7f6",
        "on-background": "#313330",
        "error-container": "#fa746f",
        "background": "#fbf9f6",
        "error": "#a83836",
        "surface-container-lowest": "#ffffff",
        "primary-dim": "#4c545e",
        "tertiary-container": "#f7ad84",
        "on-error-container": "#6e0a12"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        sans: ["Manrope", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
